spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
spring.datasource.username=test
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

spring.kafka.bootstrap-servers=${spring.embedded.kafka.brokers}
# spring.kafka.consumer.auto-offset-reset=earliest
# spring.kafka.consumer.group-id=test-group

# spring.jpa.hibernate.ddl-auto=create-drop
logging.level.org.hibernate.SQL=DEBUG

# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
