spring.application.name=kafka-listener

spring.kafka.bootstrap-servers=dapp-kafka:9092
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
# spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

spring.kafka.consumer.enable-auto-commit=false
spring.kafka.listener.ack-mode=manual-immediate

spring.datasource.url=jdbc:postgresql://dapp-profile-service-db:5432/dapp_profile_service
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.properties.spring.json.use.type.info.headers=false
spring.kafka.consumer.properties.spring.json.value.default.type=com.dapp.profileservice.kafka_listener.model.EventDTO

spring.jackson.datatype.datetime.write-dates-as-timestamps=true

# Globally fails if JSON contains "property": null
# spring.jackson.deserialization.fail-on-null-for-primitives=true
# spring.jackson.default-property-inclusion=non_null

# Strictly throws an exception if the @JsonSubTypes discriminator key is completely missing
# spring.jackson.deserialization.fail-on-missing-external-type-id-property=true

# 1. Direct the main deserializer to the Error Handling wrapper
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer

# 2. Tell the wrapper to delegate its work to the JsonDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer

