spring.application.name=api

spring.datasource.url=jdbc:postgresql://dapp-profile-service-db:5432/dapp_profile_service
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver